[env]
TERM = "xterm-256color"

[font]
size = 14.0

[font.normal]
family = "Inconsolata"
style = "Medium"

[scrolling]
history = 100000

[window]
opacity = 0.95
title = "Terminal"

[window.dimensions]
columns = 120
lines = 28

[window.padding]
x = 20
y = 10
