mirror:
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
  script:
    - eval $(ssh-agent -s)
    - ssh-add <(echo "$PRIVATE_DEPLOY_KEY")
    - git push git@github.com:srynot4sale/dotfiles.git HEAD:master
